version: "3.7"
name: lms
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: ahrechanychenko/course-project-lms:poc
    command: bash entrypoint.sh 123
    environment:
      - SHELL=/bin/bash
    working_dir: /usr/app/lms
    volumes:
      - type: bind
        source: ./entrypoint.sh
        target: /usr/app/lms/entrypoint.sh
    ports:
      - 8000:8000
      - 9000:9000

volumes:
  mariadb-data:
