#ustomize
name: Deploy

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    branches:
      - develop


env:
  IMAGE: lms

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: test build
    deploy:
      name: test deploy
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test manual approve
        run: echo "this is a test"
